[tool.poetry]
name = "poetry-export-plugin"
version = "0.3.0"
description = "Poetry plugin to export the dependencies to various formats"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "poetry_export_plugin", from = "src" }
]

include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.6"
poetry = "^1.2.0a2"

[tool.poetry.dev-dependencies]
black = { version = "^21.8b0", markers = "python_full_version >= '3.6.2' and python_version < '4.0' and implementation_name != 'pypy'" }
isort = { version = "^5.9.3", python = "^3.6.1" }
pre-commit = { version = "^2.6", python = "^3.6.1" }
pytest = "^6.2.3"
pytest-mock = "^3.6.1"

[tool.poetry.plugins."poetry.application.plugin"]
export = "poetry_export_plugin.plugins:ExportApplicationPlugin"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
